### ISSUE TITLE
RN 0.77 issue

### ISSUE THREAD

**Issue by d97893** [JimmyDaddy/react-native-image-marker#242]
Getting error after upgrading react native version to 0.77. Kindly need solution to fix this issue

Execution failed for task ':react-native-image-marker:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
> Compilation error. See log for more details

**Comment by codenads** [comment]
Same here

**Comment by d97893** [comment]
@bhanwarsuthar not yet

**Comment by AnamikaDeb25** [comment]
facing the same issue

**Comment by saeculumBhaveshB** [comment]
facing the same issue

**Comment by d97893** [comment]
[react-native-image-marker.zip](https://github.com/user-attachments/files/18904187/react-native-image-marker.zip)

After installing the latest version of react-native-image-marker using a zip file to replace. The issue has resolved for me.

**Installed plugin version**
"react-native": "0.77.0",
"react-native-image-marker": "^1.2.6",
