### ISSUE TITLE
I am getting too much "Connot Find Symbol Variable" error in Android Build

### ISSUE THREAD

**Issue by alperen** [JimmyDaddy/react-native-image-marker#10]
Hi,

When i try to getting build, i have some errors in your package. I am already linked package and installed successfully. Please help me. Thank you.

You can see my logs in here: `[http://prntscr.com/imamey](http://prntscr.com/imamey)`

> Error:(134, 36) error: cannot find symbol variable ReactFontManager
> Error:(267, 35) error: cannot find symbol variable ReactFontManager
> Error:(274, 13) error: cannot find symbol variable textPaint
> Error:(278, 61) error: cannot find symbol variable textBounds
> Error:(278, 13) error: cannot find symbol variable textPaint
> Error:(279, 13) error: cannot find symbol variable textPaint
> Error:(280, 58) error: cannot find symbol variable textBounds
> Error:(280, 78) error: cannot find symbol variable textBounds
> Error:(280, 99) error: cannot find symbol variable width
> Error:(280, 106) error: cannot find symbol variable height
> Error:(282, 59) error: cannot find symbol variable textPaint
> Error:(282, 13) error: cannot find symbol variable canvas
> Error:(284, 13) error: cannot find symbol variable canvas
> Error:(285, 13) error: cannot find symbol variable canvas

I am working on RN 0.53.3

**Comment by JimmyDaddy** [comment]
@alperen Sorry for the late response. What's the RN version of your project?

**Comment by JimmyDaddy** [comment]
Hi, I fixed this problem. The new version is `0.1.3` you can update to this version, the problem will be resolved. I'm sorry for this bug.

**Comment by alperen** [comment]
thanks for your interest. it's fixed.
